### ISSUE TITLE
Not nice hover animation 

### ISSUE THREAD

**Issue by rudnitskih** [AnnaSakivska/uber-eats-react#16]
![image](https://user-images.githubusercontent.com/8848858/60761245-57f34f00-a04d-11e9-8848-54a3956d641b.png)

**Comment by rudnitskih** [comment]
Check for example Vlad's impl:
http://uber-eats-ruchkovlad.surge.sh/

**Comment by scandy5** [comment]
http://uber-eats-masterluiji19.surge.sh/ Мне вот тут нравится

**Comment by rudnitskih** [comment]
да, у Макса еще лучше только серый background не нужен

**Comment by scandy5** [comment]
done, can be closed
