### ISSUE TITLE
Называй папки так же само как и файл/компонент

### ISSUE THREAD

**Issue by rudnitskih** [AnnaSakivska/uber-eats-react#23]
![image](https://user-images.githubusercontent.com/8848858/60764957-7aac5480-a09b-11e9-972c-410b4da7b6af.png)

**Comment by rudnitskih** [comment]
![image](https://user-images.githubusercontent.com/8848858/60765028-4b4a1780-a09c-11e9-8097-859be7c172d9.png)

![image](https://user-images.githubusercontent.com/8848858/60765030-50a76200-a09c-11e9-88cd-085f1899e7c8.png)

И куча других примеров - перепроверь все компоненты

**Comment by scandy5** [comment]
done
